# Generated by Django 4.2.2 on 2023-06-30 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0002_hotel_created_at_hotel_is_deleted_hotel_uid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
