# Generated by Django 4.2.2 on 2023-06-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
