# Generated by Django 4.2.2 on 2023-06-30 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0008_expensesource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensesource',
            name='abbreviation',
        ),
    ]
