# Generated by Django 4.2.2 on 2023-07-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bms', '0011_mainxaction_amount_due_mainxaction_is_due_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainxaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
